### ISSUE TITLE
Documentation: what does noise2fast do?

### ISSUE THREAD

**Issue by haesleinhuepf** [pelletierlab/Noise2Fast#1]
Hi @pelletierlab ,

I just found this repository and it looks super interesting. However, from the readme it is hard to guess what noise2fast does and for what kind of data it can be used. I presume it is related to this preprint: https://arxiv.org/abs/2108.10209

Maybe it is worth to copy the abstract from the paper over to the readme and link the paper for those who are interested in further details? :-)

Thanks!

Best,
Robert

**Comment by pelletierlab** [comment]
Done. Thanks for the suggestion!
